openapi: 3.0.4 # The version of the OpenAPI Specification
info:
  title: Sample API
  description: Optional multiline description in CommonMark.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Main (production) server
paths:
  /users:
    get:
      summary: Returns a list of users.
      responses:
        "200": # status code
          description: A JSON array of user names.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
